<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#取得过去3个月的交易日序列（降序排列-）" data-toc-modified-id="取得过去3个月的交易日序列（降序排列-）-0.0.1"><span class="toc-item-num">0.0.1&nbsp;&nbsp;</span>取得过去3个月的交易日序列（降序排列 ）</a></span></li><li><span><a href="#取得个股过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)" data-toc-modified-id="取得个股过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)-0.0.2"><span class="toc-item-num">0.0.2&nbsp;&nbsp;</span>取得个股过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)</a></span></li><li><span><a href="#计算个股的$r_t^{am}$数组和$r_t^{pm}$数组，并拼接为一个array" data-toc-modified-id="计算个股的$r_t^{am}$数组和$r_t^{pm}$数组，并拼接为一个array-0.0.3"><span class="toc-item-num">0.0.3&nbsp;&nbsp;</span>计算个股的$r_t^{am}$数组和$r_t^{pm}$数组，并拼接为一个array</a></span></li><li><span><a href="#取得指数过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)" data-toc-modified-id="取得指数过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)-0.0.4"><span class="toc-item-num">0.0.4&nbsp;&nbsp;</span>取得指数过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)</a></span></li><li><span><a href="#计算指数$R_t^{am}$数组和$R_t^{pm}$数组，并拼接为一个array" data-toc-modified-id="计算指数$R_t^{am}$数组和$R_t^{pm}$数组，并拼接为一个array-0.0.5"><span class="toc-item-num">0.0.5&nbsp;&nbsp;</span>计算指数$R_t^{am}$数组和$R_t^{pm}$数组，并拼接为一个array</a></span></li><li><span><a href="#将40组(r,R)的收益率数据进行线性回归" data-toc-modified-id="将40组(r,R)的收益率数据进行线性回归-0.0.6"><span class="toc-item-num">0.0.6&nbsp;&nbsp;</span>将40组(r,R)的收益率数据进行线性回归</a></span><ul class="toc-item"><li><span><a href="#首先把指数收益率数据加上常数项" data-toc-modified-id="首先把指数收益率数据加上常数项-0.0.6.1"><span class="toc-item-num">0.0.6.1&nbsp;&nbsp;</span>首先把指数收益率数据加上常数项</a></span></li><li><span><a href="#进行线性回归" data-toc-modified-id="进行线性回归-0.0.6.2"><span class="toc-item-num">0.0.6.2&nbsp;&nbsp;</span>进行线性回归</a></span></li></ul></li><li><span><a href="#计算stat统计量" data-toc-modified-id="计算stat统计量-0.0.7"><span class="toc-item-num">0.0.7&nbsp;&nbsp;</span>计算stat统计量</a></span></li></ul></li></ul></li></ul></div>

In [56]:
import datetime
import pandas as pd
from pandas import DataFrame
from pandas import Series
import numpy as np
import statsmodels.api as sm
from jaqs.data.dataapi import DataApi
api = DataApi(addr='tcp://data.tushare.org:8910')
api.login("13811931480", "eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MTI4Nzk0NTI2MjkiLCJpc3MiOiJhdXRoMCIsImlkIjoiMTM4MTE5MzE0ODAifQ.I0SXsA1bK--fbGu0B5Is2xdKOjALAeWBJRX6GdVmUL8")

('username: 13811931480', '0,')

### 取得过去3个月的交易日序列（降序排列 ）

In [3]:
end_date = datetime.datetime(2017, 12, 8)
start_date = end_date - datetime.timedelta(days=90)
df_trading_day, msg = api.query(
                                view="jz.secTradeCal",
                                fields="date,istradeday,isweekday,isholiday",
                                filter="start_date=%s&end_date=%s" % (start_date.strftime('%Y%m%d'), end_date.strftime('%Y%m%d')),
                                data_format='pandas')
df_trading_day.sort_values(by='trade_date', ascending=False, inplace=True)
df_trading_day.iloc[:21]

   isholiday istradeday isweekday  trade_date
59         F          T         T    20171208
58         F          T         T    20171207
57         F          T         T    20171206
56         F          T         T    20171205
55         F          T         T    20171204
54         F          T         T    20171201
53         F          T         T    20171130
52         F          T         T    20171129
51         F          T         T    20171128
50         F          T         T    20171127
49         F          T         T    20171124
48         F          T         T    20171123
47         F          T         T    20171122
46         F          T         T    20171121
45         F          T         T    20171120
44         F          T         T    20171117
43         F          T         T    20171116
42         F          T         T    20171115
41         F          T         T    20171114
40         F          T         T    20171113
39         F          T         T    20171110

### 取得个股过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)
开盘价：为09:31分钟线的开盘价

中午收盘价：为11:30分钟线的收盘价

当天收盘价：为15:00分钟线的收盘价

数据格式：DataFrame，按日期升序排列

In [3]:
mkt_1m_data = DataFrame()
mkt_data_header = ['date', 'open', 'mid_close', 'close']
k = 0
for _, trading_day_info in df_trading_day.iterrows():
    df_1m_mkt, msg = api.bar(symbol = '600000.SH',
                             trade_date = trading_day_info.trade_date,
                             freq = '1M',
                             start_time = 92500,
                             end_time = 150000,
                             fields='')
#     print(msg)
    s = Series([str(trading_day_info.trade_date), df_1m_mkt[df_1m_mkt.time==93100].iloc[0].open,df_1m_mkt[df_1m_mkt.time==113000].iloc[0].close,df_1m_mkt[df_1m_mkt.time==150000].iloc[0].close], index=mkt_data_header)
#     print(s)
    mkt_1m_data = mkt_1m_data.append(s,ignore_index=True)
    k += 1
    if k > 20:
        break
mkt_1m_data.sort_values(by='date',inplace=True)
mkt_1m_data.reset_index(drop=True, inplace=True)
mkt_1m_data[mkt_data_header]

        date   open  mid_close  close
0   20171110  12.54      12.54  12.63
1   20171113  12.65      12.79  12.77
2   20171114  12.76      12.62  12.59
3   20171115  12.60      12.58  12.61
4   20171116  12.57      12.46  12.39
5   20171117  12.38      12.42  12.79
6   20171120  12.70      12.68  12.85
7   20171121  12.81      13.06  12.94
8   20171122  13.00      13.29  13.24
9   20171123  13.24      13.20  13.07
10  20171124  13.11      12.98  13.08
11  20171127  13.09      12.84  13.07
12  20171128  13.03      12.94  12.95
13  20171129  12.95      12.89  12.90
14  20171130  12.91      12.88  12.91
15  20171201  12.93      12.81  12.92
16  20171204  12.87      12.86  12.93
17  20171205  12.92      13.10  13.17
18  20171206  13.12      13.03  12.96
19  20171207  12.95      12.94  12.96
20  20171208  12.98      12.94  12.92

### 计算个股的$r_t^{am}$数组和$r_t^{pm}$数组，并拼接为一个array
拼接后的收益率array，上半部分为$r_t^{am}$，下半部分为$r_t^{pm}$

In [4]:
r_am_array = np.zeros((20,1))
r_pm_array = np.zeros((20,1))
for ind in mkt_1m_data.index[1:]:
    r_am_array[ind-1] = mkt_1m_data.loc[ind, 'mid_close'] / mkt_1m_data.loc[ind-1,'close']-1
    r_pm_array[ind-1] = mkt_1m_data.loc[ind, 'close'] / mkt_1m_data.loc[ind, 'mid_close'] - 1
r_ret_array = np.concatenate((r_am_array,r_pm_array),axis=0)
print(r_ret_array)
assert r_ret_array.shape == (40,1)

[[ 0.01266825]
 [-0.01174628]
 [-0.00079428]
 [-0.01189532]
 [ 0.00242131]
 [-0.00860047]
 [ 0.01634241]
 [ 0.02704791]
 [-0.00302115]
 [-0.006886  ]
 [-0.01834862]
 [-0.00994644]
 [-0.0046332 ]
 [-0.00155039]
 [-0.00774593]
 [-0.00464396]
 [ 0.01314772]
 [-0.01063022]
 [-0.00154321]
 [-0.00154321]
 [-0.00156372]
 [-0.00237718]
 [ 0.00238474]
 [-0.00561798]
 [ 0.02979066]
 [ 0.01340694]
 [-0.00918836]
 [-0.00376223]
 [-0.00984848]
 [ 0.00770416]
 [ 0.01791277]
 [ 0.0007728 ]
 [ 0.0007758 ]
 [ 0.00232919]
 [ 0.00858704]
 [ 0.00544323]
 [ 0.00534351]
 [-0.00537222]
 [ 0.0015456 ]
 [-0.0015456 ]]

### 取得指数过去21个交易日每个交易日的开盘价(open)、中午收盘价(mid_close)、当天收盘价(close)
指数为上证综指

开盘价：为09:00分钟线的开盘价

中午收盘价：为11:30分钟线的收盘价

当天收盘价：为15:00分钟线的收盘价

数据格式：DataFrame，按日期升序排列

In [5]:
sz_1m_data = DataFrame()
k = 0
for _, trading_day_info in df_trading_day.iterrows():
    df_1m_mkt, msg = api.bar(symbol = '000001.SH',
                             trade_date = trading_day_info.trade_date,
                             freq = '1M',
                             start_time = 92500,
                             end_time = 150000,
                             fields='')
#     print(msg)
    s = Series([str(trading_day_info.trade_date), df_1m_mkt[df_1m_mkt.time==93100].iloc[0].open,df_1m_mkt[df_1m_mkt.time==113000].iloc[0].close,df_1m_mkt[df_1m_mkt.time==150000].iloc[0].close], index=mkt_data_header)
#     print(s)
    sz_1m_data = sz_1m_data.append(s,ignore_index=True)
    k += 1
    if k > 20:
        break
sz_1m_data.sort_values(by='date',inplace=True)
sz_1m_data.reset_index(drop=True, inplace=True)
sz_1m_data[mkt_data_header]

        date       open  mid_close      close
0   20171110  3423.1846  3426.0797  3432.8380
1   20171113  3435.1839  3443.1886  3448.4949
2   20171114  3446.5453  3432.7270  3429.9277
3   20171115  3416.2112  3405.2025  3402.7771
4   20171116  3393.1937  3399.1685  3399.6192
5   20171117  3392.6834  3380.1583  3382.4726
6   20171120  3361.3563  3355.0089  3393.0334
7   20171121  3382.3595  3405.9444  3411.1751
8   20171122  3417.3313  3428.3703  3430.4885
9   20171123  3425.0093  3400.3626  3353.0203
10  20171124  3340.3842  3332.6335  3353.3206
11  20171127  3346.6567  3326.9381  3322.4250
12  20171128  3311.2322  3305.5256  3333.5767
13  20171129  3335.5671  3317.3499  3337.5056
14  20171130  3328.6427  3329.1834  3316.4674
15  20171201  3315.1051  3305.7149  3317.4417
16  20171204  3310.3814  3321.6872  3309.6486
17  20171205  3301.6906  3311.3578  3303.3755
18  20171206  3291.3128  3283.7861  3294.0319
19  20171207  3283.2791  3272.7971  3271.6886
20  20171208  3264.4776  3278.5236  3290.2046

### 计算指数$R_t^{am}$数组和$R_t^{pm}$数组，并拼接为一个array
拼接后的收益率array，上半部分为$R_t^{am}$，下半部分为$R_t^{pm}$

In [6]:
sz_am_array = np.zeros((20,1))
sz_pm_array = np.zeros((20,1))
for ind in sz_1m_data.index[1:]:
    sz_am_array[ind-1] = sz_1m_data.loc[ind, 'mid_close'] / sz_1m_data.loc[ind-1,'close']-1
    sz_pm_array[ind-1] = sz_1m_data.loc[ind, 'close'] / sz_1m_data.loc[ind, 'mid_close'] - 1
sz_ret_array = np.concatenate((sz_am_array,sz_pm_array),axis=0)
print(sz_ret_array)
assert sz_ret_array.shape == (40,1)

[[ 0.00301517]
 [-0.0045724 ]
 [-0.00720867]
 [-0.00106049]
 [-0.00572444]
 [-0.00811942]
 [ 0.00380515]
 [ 0.00504084]
 [-0.00878181]
 [-0.00608013]
 [-0.00786757]
 [-0.00508647]
 [-0.00486768]
 [-0.00249354]
 [-0.00324215]
 [ 0.00127975]
 [ 0.00051643]
 [-0.00593012]
 [-0.00644645]
 [ 0.00208914]
 [ 0.0015411 ]
 [-0.00081547]
 [-0.00071226]
 [ 0.00013259]
 [ 0.00068467]
 [ 0.01133365]
 [ 0.00153576]
 [ 0.00061784]
 [-0.01392272]
 [ 0.00620743]
 [-0.00135653]
 [ 0.00848612]
 [ 0.00607584]
 [-0.00381956]
 [ 0.00354743]
 [-0.00362424]
 [-0.00241058]
 [ 0.00312012]
 [-0.0003387 ]
 [ 0.00356288]]

### 将40组(r,R)的收益率数据进行线性回归
#### 首先把指数收益率数据加上常数项

In [9]:
index_ret_array = sm.add_constant(sz_ret_array)
assert index_ret_array.shape == (40,2)
print(index_ret_array)

[[  1.00000000e+00   3.01517287e-03]
 [  1.00000000e+00  -4.57240056e-03]
 [  1.00000000e+00  -7.20866507e-03]
 [  1.00000000e+00  -1.06048674e-03]
 [  1.00000000e+00  -5.72443525e-03]
 [  1.00000000e+00  -8.11941536e-03]
 [  1.00000000e+00   3.80514969e-03]
 [  1.00000000e+00   5.04084355e-03]
 [  1.00000000e+00  -8.78181052e-03]
 [  1.00000000e+00  -6.08013020e-03]
 [  1.00000000e+00  -7.86757461e-03]
 [  1.00000000e+00  -5.08646546e-03]
 [  1.00000000e+00  -4.86768461e-03]
 [  1.00000000e+00  -2.49353889e-03]
 [  1.00000000e+00  -3.24215459e-03]
 [  1.00000000e+00   1.27975120e-03]
 [  1.00000000e+00   5.16429448e-04]
 [  1.00000000e+00  -5.93011603e-03]
 [  1.00000000e+00  -6.44644637e-03]
 [  1.00000000e+00   2.08913526e-03]
 [  1.00000000e+00   1.54110059e-03]
 [  1.00000000e+00  -8.15474111e-04]
 [  1.00000000e+00  -7.12263074e-04]
 [  1.00000000e+00   1.32591250e-04]
 [  1.00000000e+00   6.84672076e-04]
 [  1.00000000e+00   1.13336510e-02]
 [  1.00000000e+00   1.53575613e-03]
 [  1.00000000e+00   6.17844578e-04]
 [  1.00000000e+00  -1.39227211e-02]
 [  1.00000000e+00   6.20743325e-03]
 [  1.00000000e+00  -1.35653260e-03]
 [  1.00000000e+00   8.48612396e-03]
 [  1.00000000e+00   6.07584385e-03]
 [  1.00000000e+00  -3.81955527e-03]
 [  1.00000000e+00   3.54743236e-03]
 [  1.00000000e+00  -3.62424252e-03]
 [  1.00000000e+00  -2.41058215e-03]
 [  1.00000000e+00   3.12011796e-03]
 [  1.00000000e+00  -3.38701107e-04]
 [  1.00000000e+00   3.56288422e-03]]

#### 进行线性回归
$r_i = \alpha + \beta R_i + \epsilon_i$

其中：$\alpha$为常数项，$\beta$为斜率，$\epsilon$为残差，$i=1,2,\dots,40$

In [16]:
apm_model = sm.OLS(r_ret_array,index_ret_array)
apm_result = apm_model.fit()
print(apm_result.summary())
print('Parameters: ', apm_result.params)
print('R2: ', apm_result.rsquared)
epsilon_array = apm_result.resid.reshape((40,1))
assert epsilon_array.shape == (40,1)
print(epsilon_array)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.255
Model:                            OLS   Adj. R-squared:                  0.235
Method:                 Least Squares   F-statistic:                     13.01
Date:                Mon, 11 Dec 2017   Prob (F-statistic):           0.000888
Time:                        19:52:53   Log-Likelihood:                 132.12
No. Observations:                  40   AIC:                            -260.2
Df Residuals:                      38   BIC:                            -256.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0017      0.001      1.143      0.260      -0.001       0.005
x1             1.0164      0.282      3.607      0.001       0.446       1.587
==============================================================================
Omnibus:                        8.896   Durbin-Watson:                   2.126
Prob(Omnibus):                  0.012   Jarque-Bera (JB):                7.793
Skew:                           0.980   Prob(JB):                       0.0203
Kurtosis:                       3.912   Cond. No.                         195.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Parameters:  [ 0.00168487  1.01637264]
R2:  0.255095239917
[[ 0.00791884]
 [-0.00878389]
 [ 0.00484754]
 [-0.01250234]
 [ 0.00655459]
 [-0.00203299]
 [ 0.01079009]
 [ 0.02023967]
 [ 0.00421957]
 [-0.00239119]
 [-0.01203711]
 [-0.00646157]
 [-0.0013707 ]
 [-0.0007009 ]
 [-0.00613557]
 [-0.00762954]
 [ 0.01093796]
 [-0.00628788]
 [ 0.00332391]
 [-0.00535142]
 [-0.00481493]
 [-0.00323323]
 [ 0.00142379]
 [-0.00743761]
 [ 0.02740991]
 [ 0.00020286]
 [-0.01243413]
 [-0.00607506]
 [ 0.00261732]
 [-0.00028978]
 [ 0.01760664]
 [-0.00953714]
 [-0.0070844 ]
 [ 0.00452641]
 [ 0.00329666]
 [ 0.00744194]
 [ 0.00610869]
 [-0.01022829]
 [ 0.00020497]
 [-0.00685169]]

### 计算stat统计量
以上得到的40个残差$\epsilon_i$中，属于上午的记为$\epsilon_t^{am}$，属于下午的记为$\epsilon_t^{pm}$，其中$t=1,2,\dots,20$，计算每日上午与下午残差的差值

$$\delta_t=\epsilon_t^{am} - \epsilon_t^{pm}$$

为了衡量上午与下午残差的差异程度，设计统计量stat：

$$stat = \frac{\mu(\delta_t)}{\sigma(\delta_t)\sqrt{N}}$$

其中，$\mu$为均值，$\sigma$为标准差，N=20。总的来说统计量stat反映了剔除市场影响后股价行为上午与下午的差异度。stat数值大（小）于0越多，则股票在上午的表现越好（差）于下午。

In [35]:
# print(np.column_stack((epsilon_array[:20], epsilon_array[20:])))
delta_array = epsilon_array[:20] - epsilon_array[20:]
# print(delta_array)
delta_avg = np.mean(delta_array)
# print(delta_avg)
delta_std = np.std(delta_array)
# print(delta_std)
stat = delta_avg/delta_std/np.sqrt(20.0)
print('stat = ', stat)

stat =  -0.00502561082108

In [90]:
t = 1
df_basics, msg = api.query(
                           view="jz.instrumentInfo",
                           fields="status,list_date,name,market",
                           filter="inst_type=1&status=1&market=SH,SZ&symbol=",
                           data_format='pandas')
# print(msg=='0,')
df_basics.symbol = df_basics.symbol.map(lambda x:x.split('.')[0])
df_basics[df_basics.list_date < '20121002'].shape
# print(df_basics.shape)
# stock_basics = df_basics[['symbol','name','status','market','list_date']]
# print(stock_basics.head(10))

(2449, 5)

In [116]:
from multiprocessing import Process, Queue, Pool, Manager
import os, time, random

# 写数据进程执行的代码:
def write(q, i):
    print('Process to write: %s' % os.getpid())
#     for value in ['A', 'B', 'C']:
    for value in [('600000',0.1),('000001',1.1),('002024',2.1),('300276',3.1)]:
        print('Task %d, Put (%s, %.2f) to queue...' % (i, value[0], value[1]))
        q.put(value)
        time.sleep(random.random())
        
def write2(q):
    print('Process to write: %s' % os.getpid())
#     for value in ['A', 'B', 'C']:
    for value in [('600000',10.1),('000001',11.1),('002024',12.1),('300276',13.1)]:
        print('Put (%s, %.2f) to queue...' % (value[0], value[1]))
        q.put(value)
        time.sleep(random.random())
        
def long_time_task(name):
    print('Run task %s (%s)...' % (name, os.getpid()))
    start = time.time()
    time.sleep(random.random() * 3)
    end = time.time()
    print('Task %s runs %0.2f seconds.' % (name, (end - start)))

# 读数据进程执行的代码:
def read(q):
    print('Process to read: %s' % os.getpid())
    while True:
        value = q.get(True)
        print('Get (%s, %.2f) from queue.' % (value[0], value[1]))

if __name__=='__main__':
    # 父进程创建Queue，并传给各个子进程：
    manager = Manager()
    q = manager.Queue()
#     pw1 = Process(target=write1, args=(q,))
#     pw2 = Process(target=write2, args=(q,))
#     pr = Process(target=read, args=(q,))
    # 启动子进程pw，写入:
#     pw1.start()
#     pw2.start()
    # 启动子进程pr，读取:
#     pr.start()
    # 等待pw结束:
#     pw1.join()
#     pw2.join()
    # pr进程里是死循环，无法等待其结束，只能强行终止:
#     pr.terminate()


    print('Parent process %s.' % os.getpid())
    p = Pool(4)
    for i in range(8):
        p.apply_async(write1, args=(q,i,))
#         p.apply_async(long_time_task, args=(i,))
    print('Waiting for all subprocesses done...')
    p.close()
    p.join()
    print('All subprocesses done.')

Parent process 27415.
Process to write: 58418
Process to write: 58419
Task 0, Put (600000, 0.10) to queue...
Task 1, Put (600000, 0.10) to queue...
Process to write: 58420
Task 2, Put (600000, 0.10) to queue...
Process to write: 58421
Task 3, Put (600000, 0.10) to queue...
Task 1, Put (000001, 1.10) to queue...
Task 1, Put (002024, 2.10) to queue...
Waiting for all subprocesses done...
Task 3, Put (000001, 1.10) to queue...
Task 1, Put (300276, 3.10) to queue...
Process to write: 58419
Task 4, Put (600000, 0.10) to queue...
Task 2, Put (000001, 1.10) to queue...
Task 3, Put (002024, 2.10) to queue...
Task 4, Put (000001, 1.10) to queue...
Task 0, Put (000001, 1.10) to queue...
Task 0, Put (002024, 2.10) to queue...
Task 4, Put (002024, 2.10) to queue...
Task 0, Put (300276, 3.10) to queue...
Task 3, Put (300276, 3.10) to queue...
Task 2, Put (002024, 2.10) to queue...
Process to write: 58418
Task 5, Put (600000, 0.10) to queue...
Task 4, Put (300276, 3.10) to queue...
Process to write: 58421
Task 6, Put (600000, 0.10) to queue...
Task 2, Put (300276, 3.10) to queue...
Process to write: 58419
Task 7, Put (600000, 0.10) to queue...
Task 5, Put (000001, 1.10) to queue...
Task 5, Put (002024, 2.10) to queue...
Task 6, Put (000001, 1.10) to queue...
Task 6, Put (002024, 2.10) to queue...
Task 6, Put (300276, 3.10) to queue...
Task 7, Put (000001, 1.10) to queue...
Task 7, Put (002024, 2.10) to queue...
Task 5, Put (300276, 3.10) to queue...
Task 7, Put (300276, 3.10) to queue...
All subprocesses done.

In [103]:
from multiprocessing import Pool
import os, time, random

def long_time_task(name):
    print('Run task %s (%s)...' % (name, os.getpid()))
    start = time.time()
    time.sleep(random.random() * 3)
    end = time.time()
    print('Task %s runs %0.2f seconds.' % (name, (end - start)))

if __name__=='__main__':
    print('Parent process %s.' % os.getpid())
    p = Pool(4)
    for i in range(5):
        p.apply_async(long_time_task, args=(i,))
    print('Waiting for all subprocesses done...')
    p.close()
    p.join()
    print('All subprocesses done.')

Parent process 27415.
Run task 1 (56802)...
Run task 3 (56804)...
Run task 2 (56803)...
Run task 0 (56801)...
Waiting for all subprocesses done...
Task 2 runs 0.71 seconds.
Run task 4 (56803)...
Task 1 runs 1.00 seconds.
Task 4 runs 0.94 seconds.
Task 0 runs 1.67 seconds.
Task 3 runs 2.50 seconds.
All subprocesses done.